server :
  port : 8888
  servlet :
    context-path : /
    session :
      timeout : 30
  tomcat :
    uriencoding : utf-8
    max-threads : 500
  ssl :
    key-store : xdq.12
    key-alias : tomcathttps
    key-store-password : 123456

book :
  si :
    name : 三国演义
    author : 罗贯中
    price : 30








